/*==============================================================================
  AgriERP  |  02_security.sql   (PostgreSQL)
  ------------------------------------------------------------------------------
  Users, roles, granular permissions and JWT refresh-token storage.
  PostgreSQL parallel of database/scripts/02_Security.sql.

  Foreign keys are declared centrally in 80_foreign_keys.sql (deferred so table
  creation never depends on run order). ROWVERSION columns are intentionally
  absent - concurrency is the system xmin column (see EF HasRowVersionConcurrency).
==============================================================================*/

CREATE TABLE "Roles"
(
    "RoleId"         int          GENERATED BY DEFAULT AS IDENTITY,
    "RoleName"       varchar(50)  NOT NULL,
    "NormalizedName" varchar(50)  GENERATED ALWAYS AS (upper("RoleName")) STORED,
    "Description"    varchar(250),
    "IsSystemRole"   boolean      NOT NULL DEFAULT false,
    "IsActive"       boolean      NOT NULL DEFAULT true,
    "CreatedAt"      timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"      int,
    "UpdatedAt"      timestamp(3),
    "UpdatedBy"      int,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId"),
    CONSTRAINT "UQ_Roles_RoleName" UNIQUE ("RoleName")
);

CREATE TABLE "Permissions"
(
    "PermissionId"   int          GENERATED BY DEFAULT AS IDENTITY,
    "PermissionCode" varchar(100) NOT NULL,
    "Module"         varchar(50)  NOT NULL,
    "DisplayName"    varchar(120) NOT NULL,
    "Description"    varchar(250),
    "DisplayOrder"   int          NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("PermissionId"),
    CONSTRAINT "UQ_Permissions_Code" UNIQUE ("PermissionCode")
);

CREATE INDEX "IX_Permissions_Module" ON "Permissions" ("Module", "DisplayOrder");

CREATE TABLE "RolePermissions"
(
    "RoleId"       int          NOT NULL,
    "PermissionId" int          NOT NULL,
    "GrantedAt"    timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "GrantedBy"    int,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId")
);

CREATE INDEX "IX_RolePermissions_PermissionId"
    ON "RolePermissions" ("PermissionId") INCLUDE ("RoleId");

CREATE TABLE "Users"
(
    "UserId"               int          GENERATED BY DEFAULT AS IDENTITY,
    "UserName"             varchar(60)  NOT NULL,
    "NormalizedUserName"   varchar(60)  GENERATED ALWAYS AS (upper("UserName")) STORED,
    "Email"                varchar(150),
    "NormalizedEmail"      varchar(150) GENERATED ALWAYS AS (upper("Email")) STORED,
    "PasswordHash"         varchar(300) NOT NULL,
    "SecurityStamp"        uuid         NOT NULL DEFAULT gen_random_uuid(),
    "FullName"             varchar(120) NOT NULL,
    "Mobile"               varchar(15),
    "RoleId"               int          NOT NULL,
    "AvatarPath"           varchar(300),
    "MustChangePassword"   boolean      NOT NULL DEFAULT false,
    "LastLoginAt"          timestamp(3),
    "LastPasswordChangeAt" timestamp(3),
    "AccessFailedCount"    int          NOT NULL DEFAULT 0,
    "LockoutEndAt"         timestamp(3),
    "IsActive"             boolean      NOT NULL DEFAULT true,
    "IsDeleted"            boolean      NOT NULL DEFAULT false,
    "CreatedAt"            timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"            int,
    "UpdatedAt"            timestamp(3),
    "UpdatedBy"            int,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE UNIQUE INDEX "UQ_Users_UserName"
    ON "Users" ("NormalizedUserName") WHERE "IsDeleted" = false;

CREATE UNIQUE INDEX "UQ_Users_Email"
    ON "Users" ("NormalizedEmail") WHERE "IsDeleted" = false AND "Email" IS NOT NULL;

CREATE INDEX "IX_Users_RoleId"
    ON "Users" ("RoleId") INCLUDE ("FullName", "IsActive") WHERE "IsDeleted" = false;

CREATE TABLE "UserRefreshTokens"
(
    "RefreshTokenId"    bigint       GENERATED BY DEFAULT AS IDENTITY,
    "UserId"            int          NOT NULL,
    "TokenHash"         bytea        NOT NULL,
    "ExpiresAt"         timestamp(3) NOT NULL,
    "CreatedAt"         timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedByIp"       varchar(45),
    "UserAgent"         varchar(300),
    "RevokedAt"         timestamp(3),
    "RevokedByIp"       varchar(45),
    "ReplacedByTokenId" bigint,
    CONSTRAINT "PK_UserRefreshTokens" PRIMARY KEY ("RefreshTokenId")
);

CREATE UNIQUE INDEX "UQ_UserRefreshTokens_TokenHash"
    ON "UserRefreshTokens" ("TokenHash");

CREATE INDEX "IX_UserRefreshTokens_UserId_Active"
    ON "UserRefreshTokens" ("UserId", "ExpiresAt") WHERE "RevokedAt" IS NULL;

CREATE TABLE "UserPasswordResets"
(
    "PasswordResetId" bigint       GENERATED BY DEFAULT AS IDENTITY,
    "UserId"          int          NOT NULL,
    "TokenHash"       bytea        NOT NULL,
    "ExpiresAt"       timestamp(3) NOT NULL,
    "UsedAt"          timestamp(3),
    "RequestedAt"     timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "RequestedByIp"   varchar(45),
    CONSTRAINT "PK_UserPasswordResets" PRIMARY KEY ("PasswordResetId")
);

CREATE UNIQUE INDEX "UQ_UserPasswordResets_TokenHash"
    ON "UserPasswordResets" ("TokenHash");
