/*==============================================================================
  AgriERP  |  03_masters.sql   (PostgreSQL)
  ------------------------------------------------------------------------------
  Core masters: geography, units, tax, storage, vouchers, item sub-groups,
  companies, shops, warehouses, suppliers, customers.
  PostgreSQL parallel of the SQL Server masters (03_Masters + later additions:
  ItemSubGroup.ItemGroupId, Shop/Warehouse masters, Customer.FatherName).

  Foreign keys are in 80_foreign_keys.sql. ROWVERSION columns dropped (xmin).
==============================================================================*/

/* States - StateId is the GST state code, supplied (not generated). */
CREATE TABLE "States"
(
    "StateId"          int         NOT NULL,
    "StateCode"        char(2)     NOT NULL,
    "StateName"        varchar(60) NOT NULL,
    "StateAbbr"        varchar(5),
    "IsUnionTerritory" boolean     NOT NULL DEFAULT false,
    "IsActive"         boolean     NOT NULL DEFAULT true,
    CONSTRAINT "PK_States" PRIMARY KEY ("StateId"),
    CONSTRAINT "UQ_States_StateCode" UNIQUE ("StateCode"),
    CONSTRAINT "UQ_States_StateName" UNIQUE ("StateName")
);

CREATE TABLE "Units"
(
    "UnitId"       int          GENERATED BY DEFAULT AS IDENTITY,
    "UnitCode"     varchar(10)  NOT NULL,
    "UnitName"     varchar(50)  NOT NULL,
    "Description"  varchar(150),
    "AllowDecimal" boolean      NOT NULL DEFAULT true,
    "DisplayOrder" int          NOT NULL DEFAULT 0,
    "IsActive"     boolean      NOT NULL DEFAULT true,
    "IsDeleted"    boolean      NOT NULL DEFAULT false,
    "CreatedAt"    timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"    int,
    "UpdatedAt"    timestamp(3),
    "UpdatedBy"    int,
    CONSTRAINT "PK_Units" PRIMARY KEY ("UnitId")
);

CREATE UNIQUE INDEX "UQ_Units_UnitCode" ON "Units" ("UnitCode") WHERE "IsDeleted" = false;

CREATE TABLE "GstSlabs"
(
    "GstSlabId"     int          GENERATED BY DEFAULT AS IDENTITY,
    "SlabName"      varchar(30)  NOT NULL,
    "TotalRate"     numeric(6,3) NOT NULL,
    "CgstRate"      numeric(6,3) NOT NULL,
    "SgstRate"      numeric(6,3) NOT NULL,
    "IgstRate"      numeric(6,3) NOT NULL,
    "CessRate"      numeric(6,3) NOT NULL DEFAULT 0,
    "EffectiveFrom" date         NOT NULL DEFAULT '2017-07-01',
    "IsActive"      boolean      NOT NULL DEFAULT true,
    CONSTRAINT "PK_GstSlabs" PRIMARY KEY ("GstSlabId"),
    CONSTRAINT "UQ_GstSlabs_TotalRate" UNIQUE ("TotalRate"),
    CONSTRAINT "CK_GstSlabs_Split" CHECK (("CgstRate" + "SgstRate") = "TotalRate" AND "IgstRate" = "TotalRate"),
    CONSTRAINT "CK_GstSlabs_Range" CHECK ("TotalRate" >= 0 AND "TotalRate" <= 100)
);

CREATE TABLE "HsnCodes"
(
    "HsnId"            int          GENERATED BY DEFAULT AS IDENTITY,
    "HsnCode"          varchar(10)  NOT NULL,
    "Description"      varchar(250) NOT NULL,
    "DefaultGstSlabId" int,
    "IsActive"         boolean      NOT NULL DEFAULT true,
    CONSTRAINT "PK_HsnCodes" PRIMARY KEY ("HsnId"),
    CONSTRAINT "UQ_HsnCodes_HsnCode" UNIQUE ("HsnCode")
);

CREATE TABLE "StorageLocations"
(
    "LocationId"       int          GENERATED BY DEFAULT AS IDENTITY,
    "LocationCode"     varchar(20)  NOT NULL,
    "LocationName"     varchar(100) NOT NULL,
    "LocationType"     varchar(20)  NOT NULL DEFAULT 'Rack',
    "ParentLocationId" int,
    "IsDefault"        boolean      NOT NULL DEFAULT false,
    "Remarks"          varchar(300),
    "IsActive"         boolean      NOT NULL DEFAULT true,
    "IsDeleted"        boolean      NOT NULL DEFAULT false,
    "CreatedAt"        timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"        int,
    "UpdatedAt"        timestamp(3),
    "UpdatedBy"        int,
    CONSTRAINT "PK_StorageLocations" PRIMARY KEY ("LocationId"),
    CONSTRAINT "CK_StorageLocations_Type" CHECK ("LocationType" IN ('Counter','Shelf','Rack','Godown','Warehouse'))
);

CREATE UNIQUE INDEX "UQ_StorageLocations_Code"
    ON "StorageLocations" ("LocationCode") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_StorageLocations_Default"
    ON "StorageLocations" ("IsDefault") WHERE "IsDefault" = true AND "IsDeleted" = false;

CREATE TABLE "VoucherMaster"
(
    "VoucherId"    int          GENERATED BY DEFAULT AS IDENTITY,
    "VoucherCode"  varchar(20)  NOT NULL,
    "VoucherName"  varchar(60)  NOT NULL,
    "VoucherType"  varchar(30)  NOT NULL,
    "Prefix"       varchar(15)  NOT NULL,
    "DisplayOrder" int          NOT NULL DEFAULT 0,
    "IsActive"     boolean      NOT NULL DEFAULT true,
    "CreatedAt"    timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_VoucherMaster" PRIMARY KEY ("VoucherId"),
    CONSTRAINT "UQ_VoucherMaster_Code" UNIQUE ("VoucherCode")
);

CREATE TABLE "ItemSubGroupMaster"
(
    "ItemSubGroupId"       int          GENERATED BY DEFAULT AS IDENTITY,
    "ItemSubGroupCode"     varchar(20)  NOT NULL,
    "ItemSubGroupName"     varchar(100) NOT NULL,
    "ParentItemSubGroupId" int,
    "Description"          varchar(300),
    "IconName"            varchar(40),
    "DisplayOrder"        int          NOT NULL DEFAULT 0,
    "IsActive"           boolean      NOT NULL DEFAULT true,
    "IsDeleted"          boolean      NOT NULL DEFAULT false,
    "CreatedAt"          timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"          int,
    "UpdatedAt"          timestamp(3),
    "UpdatedBy"          int,
    "ItemGroupId"        int          NOT NULL,
    CONSTRAINT "PK_ItemSubGroupMaster" PRIMARY KEY ("ItemSubGroupId")
);

CREATE INDEX "IX_ItemSubGroupMaster_GroupId"
    ON "ItemSubGroupMaster" ("ItemGroupId")
    INCLUDE ("ItemSubGroupCode", "ItemSubGroupName", "DisplayOrder") WHERE "IsDeleted" = false;
CREATE INDEX "IX_ItemSubGroupMaster_ParentItemSubGroupId"
    ON "ItemSubGroupMaster" ("ParentItemSubGroupId")
    INCLUDE ("ItemSubGroupName", "DisplayOrder") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_ItemSubGroupMaster_Code"
    ON "ItemSubGroupMaster" ("ItemSubGroupCode") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_ItemSubGroupMaster_Name"
    ON "ItemSubGroupMaster" ("ItemSubGroupName") WHERE "IsDeleted" = false;

CREATE TABLE "Companies"
(
    "CompanyId"     int          GENERATED BY DEFAULT AS IDENTITY,
    "CompanyCode"   varchar(20)  NOT NULL,
    "CompanyName"   varchar(150) NOT NULL,
    "GstNumber"     varchar(15),
    "Address"       varchar(300),
    "City"          varchar(80),
    "StateId"       int,
    "Pincode"       varchar(6),
    "Phone"         varchar(15),
    "Email"         varchar(150),
    "Website"       varchar(200),
    "ContactPerson" varchar(120),
    "LogoPath"      varchar(300),
    "Remarks"       varchar(500),
    "IsActive"      boolean      NOT NULL DEFAULT true,
    "IsDeleted"     boolean      NOT NULL DEFAULT false,
    "CreatedAt"     timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"     int,
    "UpdatedAt"     timestamp(3),
    "UpdatedBy"     int,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("CompanyId"),
    CONSTRAINT "CK_Companies_Pincode" CHECK ("Pincode" IS NULL OR "Pincode" ~ '^[1-9][0-9]{5}$')
);

CREATE UNIQUE INDEX "UQ_Companies_Code" ON "Companies" ("CompanyCode") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_Companies_Name" ON "Companies" ("CompanyName") WHERE "IsDeleted" = false;

CREATE TABLE "ShopMaster"
(
    "ShopId"    int          GENERATED BY DEFAULT AS IDENTITY,
    "ShopName"  varchar(150) NOT NULL,
    "Address"   varchar(500),
    "City"      varchar(80),
    "StateId"   int,
    "GstNo"     varchar(15),
    "OwnerName" varchar(120),
    "MobileNo"  varchar(15),
    "Email"     varchar(150),
    "IsActive"  boolean      NOT NULL DEFAULT true,
    "IsDeleted" boolean      NOT NULL DEFAULT false,
    "CreatedAt" timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy" int,
    "UpdatedAt" timestamp(3),
    "UpdatedBy" int,
    CONSTRAINT "PK_ShopMaster" PRIMARY KEY ("ShopId")
);

CREATE UNIQUE INDEX "UQ_ShopMaster_Name" ON "ShopMaster" ("ShopName") WHERE "IsDeleted" = false;

CREATE TABLE "WarehouseMaster"
(
    "WarehouseId"   int          GENERATED BY DEFAULT AS IDENTITY,
    "WarehouseCode" varchar(20)  NOT NULL,
    "WarehouseName" varchar(150) NOT NULL,
    "Address"       varchar(500),
    "IsActive"      boolean      NOT NULL DEFAULT true,
    "IsDeleted"     boolean      NOT NULL DEFAULT false,
    "CreatedAt"     timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"     int,
    "UpdatedAt"     timestamp(3),
    "UpdatedBy"     int,
    CONSTRAINT "PK_WarehouseMaster" PRIMARY KEY ("WarehouseId")
);

CREATE UNIQUE INDEX "UQ_WarehouseMaster_Code" ON "WarehouseMaster" ("WarehouseCode") WHERE "IsDeleted" = false;

CREATE TABLE "WarehouseBins"
(
    "WarehouseBinId" int          GENERATED BY DEFAULT AS IDENTITY,
    "WarehouseId"    int          NOT NULL,
    "BinName"        varchar(100) NOT NULL,
    CONSTRAINT "PK_WarehouseBins" PRIMARY KEY ("WarehouseBinId")
);

CREATE INDEX "IX_WarehouseBins_WarehouseId" ON "WarehouseBins" ("WarehouseId");

CREATE TABLE "Suppliers"
(
    "SupplierId"         int          GENERATED BY DEFAULT AS IDENTITY,
    "SupplierCode"       varchar(20)  NOT NULL,
    "SupplierName"       varchar(150) NOT NULL,
    "GstNumber"          varchar(15),
    "PanNumber"          varchar(10),
    "Address"            varchar(300),
    "City"               varchar(80),
    "StateId"            int,
    "Pincode"            varchar(6),
    "Phone"              varchar(15),
    "AlternatePhone"     varchar(15),
    "Email"              varchar(150),
    "ContactPerson"      varchar(120),
    "PaymentTermDays"    int          NOT NULL DEFAULT 0,
    "CreditLimit"        numeric(18,2) NOT NULL DEFAULT 0,
    "OpeningBalance"     numeric(18,2) NOT NULL DEFAULT 0,
    "OpeningBalanceType" char(2)      NOT NULL DEFAULT 'CR',
    "OpeningBalanceDate" date,
    "BankName"           varchar(120),
    "BankAccountNumber"  varchar(30),
    "BankIfsc"           varchar(11),
    "Remarks"            varchar(500),
    "IsActive"           boolean      NOT NULL DEFAULT true,
    "IsDeleted"          boolean      NOT NULL DEFAULT false,
    "CreatedAt"          timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"          int,
    "UpdatedAt"          timestamp(3),
    "UpdatedBy"          int,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("SupplierId"),
    CONSTRAINT "CK_Suppliers_OpeningBalanceType" CHECK ("OpeningBalanceType" IN ('CR','DR')),
    CONSTRAINT "CK_Suppliers_PaymentTermDays" CHECK ("PaymentTermDays" >= 0),
    CONSTRAINT "CK_Suppliers_Pincode" CHECK ("Pincode" IS NULL OR "Pincode" ~ '^[1-9][0-9]{5}$')
);

CREATE INDEX "IX_Suppliers_Name"
    ON "Suppliers" ("SupplierName") INCLUDE ("Phone", "City", "IsActive") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_Suppliers_Code" ON "Suppliers" ("SupplierCode") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_Suppliers_GstNumber"
    ON "Suppliers" ("GstNumber") WHERE "IsDeleted" = false AND "GstNumber" IS NOT NULL;

CREATE TABLE "Customers"
(
    "CustomerId"         int          GENERATED BY DEFAULT AS IDENTITY,
    "CustomerCode"       varchar(20)  NOT NULL,
    "CustomerName"       varchar(150) NOT NULL,
    "Village"            varchar(100),
    "Mobile"             varchar(15),
    "AlternateMobile"    varchar(15),
    "GstNumber"          varchar(15),
    "Address"            varchar(300),
    "City"               varchar(80),
    "StateId"            int,
    "Pincode"            varchar(6),
    "CustomerType"       varchar(15)  NOT NULL DEFAULT 'Retail',
    "CreditLimit"        numeric(18,2) NOT NULL DEFAULT 0,
    "CreditDays"         int          NOT NULL DEFAULT 0,
    "OpeningBalance"     numeric(18,2) NOT NULL DEFAULT 0,
    "OpeningBalanceType" char(2)      NOT NULL DEFAULT 'DR',
    "OpeningBalanceDate" date,
    "Remarks"            varchar(500),
    "IsActive"           boolean      NOT NULL DEFAULT true,
    "IsDeleted"          boolean      NOT NULL DEFAULT false,
    "CreatedAt"          timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"          int,
    "UpdatedAt"          timestamp(3),
    "UpdatedBy"          int,
    "FatherName"         varchar(150),
    CONSTRAINT "PK_Customers" PRIMARY KEY ("CustomerId"),
    CONSTRAINT "CK_Customers_CustomerType" CHECK ("CustomerType" IN ('Dealer','Wholesale','Retail')),
    CONSTRAINT "CK_Customers_OpeningBalanceType" CHECK ("OpeningBalanceType" IN ('CR','DR')),
    CONSTRAINT "CK_Customers_CreditDays" CHECK ("CreditDays" >= 0),
    CONSTRAINT "CK_Customers_Pincode" CHECK ("Pincode" IS NULL OR "Pincode" ~ '^[1-9][0-9]{5}$')
);

CREATE INDEX "IX_Customers_Name"
    ON "Customers" ("CustomerName") INCLUDE ("Village", "Mobile", "IsActive") WHERE "IsDeleted" = false;
CREATE INDEX "IX_Customers_Village"
    ON "Customers" ("Village") INCLUDE ("CustomerName", "Mobile") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_Customers_Code" ON "Customers" ("CustomerCode") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_Customers_Mobile"
    ON "Customers" ("Mobile") WHERE "IsDeleted" = false AND "Mobile" IS NOT NULL;
