/*==============================================================================
  AgriERP  |  04_items.sql   (PostgreSQL)
  ------------------------------------------------------------------------------
  Item groups, dynamic group fields, items, per-item field values, batches,
  images and price history. PostgreSQL parallel of the SQL Server item scripts
  (04/14/15/16/17/21, final state).

  Foreign keys are in 80_foreign_keys.sql. ROWVERSION dropped (xmin).
  Persisted computed columns become GENERATED ... STORED.
==============================================================================*/

CREATE TABLE "ItemGroupMaster"
(
    "ItemGroupId"    int          GENERATED BY DEFAULT AS IDENTITY,
    "ItemGroupCode"  varchar(20)  NOT NULL,
    "ItemGroupName"  varchar(100) NOT NULL,
    "ItemCodePrefix" varchar(10)  NOT NULL,
    "Description"    varchar(300),
    "IconName"       varchar(50),
    "DisplayOrder"   int          NOT NULL DEFAULT 0,
    "IsActive"       boolean      NOT NULL DEFAULT true,
    "IsDeleted"      boolean      NOT NULL DEFAULT false,
    "CreatedAt"      timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"      int,
    "UpdatedAt"      timestamp(3),
    "UpdatedBy"      int,
    CONSTRAINT "PK_ItemGroupMaster" PRIMARY KEY ("ItemGroupId"),
    CONSTRAINT "CK_ItemGroupMaster_Prefix" CHECK (length(trim("ItemCodePrefix")) > 0)
);

CREATE UNIQUE INDEX "UQ_ItemGroupMaster_Code"   ON "ItemGroupMaster" ("ItemGroupCode")  WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_ItemGroupMaster_Prefix" ON "ItemGroupMaster" ("ItemCodePrefix") WHERE "IsDeleted" = false;

CREATE TABLE "ItemGroupFieldMaster"
(
    "ItemGroupFieldId" int          GENERATED BY DEFAULT AS IDENTITY,
    "ItemGroupId"      int          NOT NULL,
    "FieldName"        varchar(128) NOT NULL,
    "FieldDisplayName" varchar(100) NOT NULL,
    "HelpText"         varchar(300),
    "FieldType"        varchar(20)  NOT NULL,
    "IsStoredOnItem"   boolean      NOT NULL DEFAULT true,
    "IsDisplay"        boolean      NOT NULL DEFAULT true,
    "IsRequired"       boolean      NOT NULL DEFAULT false,
    "IsReadOnly"       boolean      NOT NULL DEFAULT false,
    "DisplayOrder"     int          NOT NULL DEFAULT 0,
    "ColumnSpan"       smallint     NOT NULL DEFAULT 1,
    "SectionName"      varchar(60),
    "DefaultValue"     varchar(200),
    "LookupSource"     varchar(60),
    "MinValue"         numeric(18,4),
    "MaxValue"         numeric(18,4),
    "MaxLength"        int,
    "UnitLabel"        varchar(30),
    "IsActive"         boolean      NOT NULL DEFAULT true,
    "IsDeleted"        boolean      NOT NULL DEFAULT false,
    "CreatedAt"        timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"        int,
    "UpdatedAt"        timestamp(3),
    "UpdatedBy"        int,
    CONSTRAINT "PK_ItemGroupFieldMaster" PRIMARY KEY ("ItemGroupFieldId"),
    CONSTRAINT "CK_ItemGroupFieldMaster_Type" CHECK ("FieldType" IN ('textarea','date','checkbox','select','decimal','number','text')),
    CONSTRAINT "CK_ItemGroupFieldMaster_Span" CHECK ("ColumnSpan" >= 1 AND "ColumnSpan" <= 4),
    CONSTRAINT "CK_ItemGroupFieldMaster_Range" CHECK ("MinValue" IS NULL OR "MaxValue" IS NULL OR "MaxValue" >= "MinValue"),
    CONSTRAINT "CK_ItemGroupFieldMaster_Lookup" CHECK ("FieldType" <> 'select' OR "LookupSource" IS NOT NULL)
);

CREATE INDEX "IX_ItemGroupFieldMaster_Group_Order"
    ON "ItemGroupFieldMaster" ("ItemGroupId", "DisplayOrder")
    INCLUDE ("FieldName", "FieldDisplayName", "FieldType", "IsStoredOnItem", "IsRequired")
    WHERE "IsDeleted" = false AND "IsDisplay" = true;
CREATE UNIQUE INDEX "UQ_ItemGroupFieldMaster_Group_Field"
    ON "ItemGroupFieldMaster" ("ItemGroupId", "FieldName") WHERE "IsDeleted" = false;

CREATE TABLE "ItemMaster"
(
    "ItemId"               int          GENERATED BY DEFAULT AS IDENTITY,
    "ItemCode"             varchar(30)  NOT NULL,
    "ItemName"             varchar(200) NOT NULL,
    "ShortName"            varchar(60),
    "TechnicalName"        varchar(200),
    "ItemSubGroupId"       int          NOT NULL,
    "CompanyId"            int,
    "Brand"                varchar(100),
    "PackingSize"          numeric(18,3),
    "PackingUnitId"        int,
    "UnitId"               int          NOT NULL,
    "HsnId"                int,
    "GstSlabId"            int          NOT NULL,
    "IsRateInclusiveOfTax" boolean      NOT NULL DEFAULT false,
    "PurchaseRate"         numeric(18,4) NOT NULL DEFAULT 0,
    "SellingRate"          numeric(18,4) NOT NULL DEFAULT 0,
    "Mrp"                  numeric(18,4) NOT NULL DEFAULT 0,
    "WholesaleRate"        numeric(18,4) NOT NULL DEFAULT 0,
    "DealerRate"           numeric(18,4) NOT NULL DEFAULT 0,
    "MinSellingRate"       numeric(18,4) NOT NULL DEFAULT 0,
    "MinStockLevel"        numeric(18,3) NOT NULL DEFAULT 0,
    "MaxStockLevel"        numeric(18,3) NOT NULL DEFAULT 0,
    "ReorderLevel"         numeric(18,3) NOT NULL DEFAULT 0,
    "IsBatchTracked"       boolean      NOT NULL DEFAULT true,
    "IsExpiryTracked"      boolean      NOT NULL DEFAULT true,
    "AllowNegativeStock"   boolean      NOT NULL DEFAULT false,
    "DefaultLocationId"    int,
    "RackNumber"           varchar(30),
    "Barcode"              varchar(50),
    "ImagePath"            varchar(300),
    "Description"          varchar(1000),
    "LicenceNumber"        varchar(50),
    "IsActive"             boolean      NOT NULL DEFAULT true,
    "IsDeleted"            boolean      NOT NULL DEFAULT false,
    "CreatedAt"            timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"            int,
    "UpdatedAt"            timestamp(3),
    "UpdatedBy"            int,
    "ItemGroupId"          int          NOT NULL,
    "PurchaseUnitId"       int,
    "StockUnitId"          int,
    CONSTRAINT "PK_ItemMaster" PRIMARY KEY ("ItemId"),
    CONSTRAINT "CK_ItemMaster_Rates" CHECK ("PurchaseRate" >= 0 AND "SellingRate" >= 0 AND "Mrp" >= 0 AND "WholesaleRate" >= 0 AND "DealerRate" >= 0 AND "MinSellingRate" >= 0),
    CONSTRAINT "CK_ItemMaster_StockLevels" CHECK ("MinStockLevel" >= 0 AND "MaxStockLevel" >= 0 AND "ReorderLevel" >= 0 AND ("MaxStockLevel" = 0 OR "MaxStockLevel" >= "MinStockLevel")),
    CONSTRAINT "CK_ItemMaster_PackingSize" CHECK ("PackingSize" IS NULL OR "PackingSize" > 0)
);

CREATE INDEX "IX_ItemMaster_CompanyId"
    ON "ItemMaster" ("CompanyId") INCLUDE ("ItemName", "ItemSubGroupId", "SellingRate", "IsActive") WHERE "IsDeleted" = false;
CREATE INDEX "IX_ItemMaster_GroupId"
    ON "ItemMaster" ("ItemGroupId") INCLUDE ("ItemName", "ItemSubGroupId", "SellingRate", "IsActive") WHERE "IsDeleted" = false;
CREATE INDEX "IX_ItemMaster_ItemName"
    ON "ItemMaster" ("ItemName") INCLUDE ("ItemCode", "ShortName", "SellingRate", "Mrp", "UnitId", "GstSlabId") WHERE "IsDeleted" = false AND "IsActive" = true;
CREATE INDEX "IX_ItemMaster_ItemSubGroupId"
    ON "ItemMaster" ("ItemSubGroupId") INCLUDE ("ItemName", "CompanyId", "SellingRate", "Mrp", "UnitId", "IsActive") WHERE "IsDeleted" = false;
CREATE INDEX "IX_ItemMaster_TechnicalName"
    ON "ItemMaster" ("TechnicalName") INCLUDE ("ItemName", "ItemId") WHERE "IsDeleted" = false AND "IsActive" = true AND "TechnicalName" IS NOT NULL;
CREATE UNIQUE INDEX "UQ_ItemMaster_Barcode"
    ON "ItemMaster" ("Barcode") WHERE "IsDeleted" = false AND "Barcode" IS NOT NULL;
CREATE UNIQUE INDEX "UQ_ItemMaster_ItemCode"
    ON "ItemMaster" ("ItemCode") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UQ_ItemMaster_Name_Company_Packing"
    ON "ItemMaster" ("ItemName", "CompanyId", "PackingSize", "PackingUnitId") NULLS NOT DISTINCT WHERE "IsDeleted" = false;

CREATE TABLE "ItemMasterDetails"
(
    "ItemDetailId"     bigint       GENERATED BY DEFAULT AS IDENTITY,
    "ItemId"           int          NOT NULL,
    "ItemGroupFieldId" int          NOT NULL,
    "FieldValue"       varchar(500),
    "CreatedAt"        timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"        int,
    "UpdatedAt"        timestamp(3),
    "UpdatedBy"        int,
    CONSTRAINT "PK_ItemMasterDetails" PRIMARY KEY ("ItemDetailId")
);

CREATE UNIQUE INDEX "UQ_ItemMasterDetails_Item_Field"
    ON "ItemMasterDetails" ("ItemId", "ItemGroupFieldId");

CREATE TABLE "ItemBatches"
(
    "BatchId"           bigint        GENERATED BY DEFAULT AS IDENTITY,
    "ItemId"            int           NOT NULL,
    "BatchNumber"       varchar(50)   NOT NULL,
    "LocationId"        int           NOT NULL,
    "ManufacturingDate" date,
    "ExpiryDate"        date,
    "PurchaseRate"      numeric(18,4) NOT NULL DEFAULT 0,
    "Mrp"               numeric(18,4) NOT NULL DEFAULT 0,
    "SellingRate"       numeric(18,4) NOT NULL DEFAULT 0,
    "InwardQty"         numeric(18,3) NOT NULL DEFAULT 0,
    "OutwardQty"        numeric(18,3) NOT NULL DEFAULT 0,
    "CurrentQty"        numeric(19,3) GENERATED ALWAYS AS ("InwardQty" - "OutwardQty") STORED,
    "Remarks"           varchar(300),
    "IsActive"          boolean       NOT NULL DEFAULT true,
    "CreatedAt"         timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"         int,
    "UpdatedAt"         timestamp(3),
    "UpdatedBy"         int,
    CONSTRAINT "PK_ItemBatches" PRIMARY KEY ("BatchId"),
    CONSTRAINT "CK_ItemBatches_Qty" CHECK ("InwardQty" >= 0 AND "OutwardQty" >= 0),
    CONSTRAINT "CK_ItemBatches_Dates" CHECK ("ManufacturingDate" IS NULL OR "ExpiryDate" IS NULL OR "ExpiryDate" >= "ManufacturingDate")
);

CREATE INDEX "IX_ItemBatches_ExpiryDate"
    ON "ItemBatches" ("ExpiryDate") INCLUDE ("ItemId", "BatchNumber", "CurrentQty", "PurchaseRate") WHERE "ExpiryDate" IS NOT NULL;
CREATE INDEX "IX_ItemBatches_Item_Expiry"
    ON "ItemBatches" ("ItemId", "ExpiryDate") INCLUDE ("BatchId", "BatchNumber", "CurrentQty", "PurchaseRate", "Mrp", "LocationId");
CREATE INDEX "IX_ItemBatches_LocationId"
    ON "ItemBatches" ("LocationId") INCLUDE ("ItemId", "CurrentQty");
CREATE UNIQUE INDEX "UQ_ItemBatches_Item_Batch_Location"
    ON "ItemBatches" ("ItemId", "BatchNumber", "LocationId");

CREATE TABLE "ItemImages"
(
    "ItemImageId"   bigint       GENERATED BY DEFAULT AS IDENTITY,
    "ItemId"        int          NOT NULL,
    "FilePath"      varchar(300) NOT NULL,
    "FileName"      varchar(200),
    "ContentType"   varchar(100),
    "FileSizeBytes" bigint,
    "IsPrimary"     boolean      NOT NULL DEFAULT false,
    "DisplayOrder"  int          NOT NULL DEFAULT 0,
    "CreatedAt"     timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"     int,
    CONSTRAINT "PK_ItemImages" PRIMARY KEY ("ItemImageId")
);

CREATE INDEX "IX_ItemImages_ItemId" ON "ItemImages" ("ItemId", "DisplayOrder");
CREATE UNIQUE INDEX "UQ_ItemImages_Primary" ON "ItemImages" ("ItemId") WHERE "IsPrimary" = true;

CREATE TABLE "ItemPriceHistory"
(
    "PriceHistoryId"  bigint       GENERATED BY DEFAULT AS IDENTITY,
    "ItemId"          int          NOT NULL,
    "ChangedAt"       timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "ChangedBy"       int,
    "ChangeSource"    varchar(20)  NOT NULL DEFAULT 'Manual',
    "ReferenceNumber" varchar(30),
    "OldPurchaseRate" numeric(18,4),
    "NewPurchaseRate" numeric(18,4),
    "OldSellingRate"  numeric(18,4),
    "NewSellingRate"  numeric(18,4),
    "OldMrp"          numeric(18,4),
    "NewMrp"          numeric(18,4),
    "Remarks"         varchar(300),
    CONSTRAINT "PK_ItemPriceHistory" PRIMARY KEY ("PriceHistoryId")
);

CREATE INDEX "IX_ItemPriceHistory_Item_Date" ON "ItemPriceHistory" ("ItemId", "ChangedAt");
