/*==============================================================================
  AgriERP  |  05_inventory.sql   (PostgreSQL)
  ------------------------------------------------------------------------------
  Transaction types, the stock journal, physical-count adjustments and inter-
  location transfers. PostgreSQL parallel of database/scripts/05_Inventory.sql
  (+ 30_AdjustmentWarehouseBin). FKs in 80_foreign_keys.sql, ROWVERSION dropped.
==============================================================================*/

/* TransactionTypes - TransactionTypeId is a small fixed code, supplied. */
CREATE TABLE "TransactionTypes"
(
    "TransactionTypeId" smallint    NOT NULL,
    "TypeCode"          varchar(30) NOT NULL,
    "TypeName"          varchar(60) NOT NULL,
    "Direction"         smallint    NOT NULL,
    "IsActive"          boolean     NOT NULL DEFAULT true,
    CONSTRAINT "PK_TransactionTypes" PRIMARY KEY ("TransactionTypeId"),
    CONSTRAINT "UQ_TransactionTypes_Code" UNIQUE ("TypeCode"),
    CONSTRAINT "CK_TransactionTypes_Direction" CHECK ("Direction" = 1 OR "Direction" = -1)
);

CREATE TABLE "StockTransactions"
(
    "StockTransactionId"    bigint        GENERATED BY DEFAULT AS IDENTITY,
    "TransactionDate"       timestamp(3)  NOT NULL,
    "TransactionTypeId"     smallint      NOT NULL,
    "ItemId"                int           NOT NULL,
    "BatchId"               bigint        NOT NULL,
    "LocationId"            int           NOT NULL,
    "Direction"             smallint      NOT NULL,
    "Quantity"              numeric(18,3) NOT NULL,
    "SignedQuantity"        numeric(24,3) GENERATED ALWAYS AS ("Quantity" * "Direction") STORED,
    "Rate"                  numeric(18,4) NOT NULL DEFAULT 0,
    "Value"                 numeric(18,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2))) STORED,
    "ReferenceType"         varchar(30),
    "ReferenceId"           bigint,
    "ReferenceDetailId"     bigint,
    "ReferenceNumber"       varchar(30),
    "ReversesTransactionId" bigint,
    "Remarks"               varchar(300),
    "FinancialYearId"       int,
    "CreatedAt"             timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"             int,
    CONSTRAINT "PK_StockTransactions" PRIMARY KEY ("StockTransactionId"),
    CONSTRAINT "CK_StockTransactions_Direction" CHECK ("Direction" = 1 OR "Direction" = -1),
    CONSTRAINT "CK_StockTransactions_Rate" CHECK ("Rate" >= 0),
    CONSTRAINT "CK_StockTransactions_Quantity" CHECK ("Quantity" > 0)
);

CREATE INDEX "IX_StockTransactions_Batch_Date"
    ON "StockTransactions" ("BatchId", "TransactionDate") INCLUDE ("SignedQuantity", "TransactionTypeId", "Rate");
CREATE INDEX "IX_StockTransactions_Date"
    ON "StockTransactions" ("TransactionDate") INCLUDE ("ItemId", "TransactionTypeId", "SignedQuantity", "Value");
CREATE INDEX "IX_StockTransactions_Product_Date"
    ON "StockTransactions" ("ItemId", "TransactionDate", "StockTransactionId")
    INCLUDE ("BatchId", "LocationId", "TransactionTypeId", "Quantity", "SignedQuantity", "Rate", "ReferenceNumber");
CREATE INDEX "IX_StockTransactions_Reference"
    ON "StockTransactions" ("ReferenceType", "ReferenceId")
    INCLUDE ("ItemId", "BatchId", "SignedQuantity", "StockTransactionId");

CREATE TABLE "StockAdjustments"
(
    "AdjustmentId"      bigint        GENERATED BY DEFAULT AS IDENTITY,
    "AdjustmentNumber"  varchar(30)   NOT NULL,
    "AdjustmentDate"    date          NOT NULL,
    "AdjustmentType"    varchar(20)   NOT NULL,
    "LocationId"        int           NOT NULL,
    "Reason"            varchar(300),
    "Remarks"           varchar(500),
    "TotalIncreaseQty"  numeric(18,3) NOT NULL DEFAULT 0,
    "TotalDecreaseQty"  numeric(18,3) NOT NULL DEFAULT 0,
    "TotalValueImpact"  numeric(18,2) NOT NULL DEFAULT 0,
    "Status"            varchar(15)   NOT NULL DEFAULT 'Draft',
    "PostedAt"          timestamp(3),
    "PostedBy"          int,
    "ApprovedBy"        int,
    "FinancialYearId"   int,
    "CreatedAt"         timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"         int,
    "UpdatedAt"         timestamp(3),
    "UpdatedBy"         int,
    CONSTRAINT "PK_StockAdjustments" PRIMARY KEY ("AdjustmentId"),
    CONSTRAINT "UQ_StockAdjustments_Number" UNIQUE ("AdjustmentNumber"),
    CONSTRAINT "CK_StockAdjustments_Type" CHECK ("AdjustmentType" IN ('Other','Opening','Expiry','Damage','Physical')),
    CONSTRAINT "CK_StockAdjustments_Status" CHECK ("Status" IN ('Cancelled','Posted','Draft'))
);

CREATE INDEX "IX_StockAdjustments_Date"
    ON "StockAdjustments" ("AdjustmentDate") INCLUDE ("AdjustmentNumber", "AdjustmentType", "Status");

CREATE TABLE "StockAdjustmentDetails"
(
    "AdjustmentDetailId" bigint        GENERATED BY DEFAULT AS IDENTITY,
    "AdjustmentId"       bigint        NOT NULL,
    "LineNumber"         int           NOT NULL,
    "ItemId"             int           NOT NULL,
    "BatchId"            bigint        NOT NULL,
    "SystemQty"          numeric(18,3) NOT NULL DEFAULT 0,
    "PhysicalQty"        numeric(18,3) NOT NULL DEFAULT 0,
    "DifferenceQty"      numeric(19,3) GENERATED ALWAYS AS ("PhysicalQty" - "SystemQty") STORED,
    "Rate"               numeric(18,4) NOT NULL DEFAULT 0,
    "ValueImpact"        numeric(18,2) GENERATED ALWAYS AS (CAST(("PhysicalQty" - "SystemQty") * "Rate" AS numeric(18,2))) STORED,
    "Reason"             varchar(300),
    "WarehouseId"        int,
    "BinName"            varchar(50),
    CONSTRAINT "PK_StockAdjustmentDetails" PRIMARY KEY ("AdjustmentDetailId"),
    CONSTRAINT "CK_StockAdjustmentDetails_Qty" CHECK ("SystemQty" >= 0 AND "PhysicalQty" >= 0)
);

CREATE INDEX "IX_StockAdjustmentDetails_AdjustmentId"
    ON "StockAdjustmentDetails" ("AdjustmentId", "LineNumber");
CREATE INDEX "IX_StockAdjustmentDetails_ProductId"
    ON "StockAdjustmentDetails" ("ItemId") INCLUDE ("BatchId", "DifferenceQty");

CREATE TABLE "StockTransfers"
(
    "TransferId"      bigint        GENERATED BY DEFAULT AS IDENTITY,
    "TransferNumber"  varchar(30)   NOT NULL,
    "TransferDate"    date          NOT NULL,
    "FromLocationId"  int           NOT NULL,
    "ToLocationId"    int           NOT NULL,
    "TotalQty"        numeric(18,3) NOT NULL DEFAULT 0,
    "TotalValue"      numeric(18,2) NOT NULL DEFAULT 0,
    "Remarks"         varchar(500),
    "Status"          varchar(15)   NOT NULL DEFAULT 'Draft',
    "PostedAt"        timestamp(3),
    "PostedBy"        int,
    "FinancialYearId" int,
    "CreatedAt"       timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"       int,
    "UpdatedAt"       timestamp(3),
    "UpdatedBy"       int,
    CONSTRAINT "PK_StockTransfers" PRIMARY KEY ("TransferId"),
    CONSTRAINT "UQ_StockTransfers_Number" UNIQUE ("TransferNumber"),
    CONSTRAINT "CK_StockTransfers_Locations" CHECK ("FromLocationId" <> "ToLocationId"),
    CONSTRAINT "CK_StockTransfers_Status" CHECK ("Status" IN ('Cancelled','Posted','Draft'))
);

CREATE INDEX "IX_StockTransfers_Date"
    ON "StockTransfers" ("TransferDate") INCLUDE ("TransferNumber", "FromLocationId", "ToLocationId", "Status");

CREATE TABLE "StockTransferDetails"
(
    "TransferDetailId" bigint        GENERATED BY DEFAULT AS IDENTITY,
    "TransferId"       bigint        NOT NULL,
    "LineNumber"       int           NOT NULL,
    "ItemId"           int           NOT NULL,
    "FromBatchId"      bigint        NOT NULL,
    "ToBatchId"        bigint,
    "Quantity"         numeric(18,3) NOT NULL,
    "Rate"             numeric(18,4) NOT NULL DEFAULT 0,
    "LineValue"        numeric(18,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2))) STORED,
    "Remarks"          varchar(300),
    CONSTRAINT "PK_StockTransferDetails" PRIMARY KEY ("TransferDetailId"),
    CONSTRAINT "CK_StockTransferDetails_Quantity" CHECK ("Quantity" > 0)
);

CREATE INDEX "IX_StockTransferDetails_ProductId"
    ON "StockTransferDetails" ("ItemId") INCLUDE ("FromBatchId", "ToBatchId", "Quantity");
CREATE INDEX "IX_StockTransferDetails_TransferId"
    ON "StockTransferDetails" ("TransferId", "LineNumber");
