/*==============================================================================
  AgriERP  |  06_purchase.sql   (PostgreSQL)
  ------------------------------------------------------------------------------
  Purchase requisitions, orders, GRN/purchases and purchase returns (headers +
  details). PostgreSQL parallel of the SQL Server purchase scripts (final state,
  incl. 18/19/22/25/31). FKs in 80_foreign_keys.sql, ROWVERSION dropped.
  Persisted totals become GENERATED ... STORED (expressions expanded to base
  columns, as PostgreSQL generated columns may not reference other generated ones).
==============================================================================*/

CREATE TABLE "PurchaseRequisitions"
(
    "RequisitionId"     bigint        GENERATED BY DEFAULT AS IDENTITY,
    "RequisitionNumber" varchar(30)   NOT NULL,
    "RequisitionDate"   date          NOT NULL,
    "LocationId"        int           NOT NULL,
    "Remarks"           varchar(500),
    "TotalQty"          numeric(18,3) NOT NULL DEFAULT 0,
    "Status"            varchar(15)   NOT NULL DEFAULT 'Open',
    "VoucherId"         int,
    "FinancialYearId"   int,
    "CreatedAt"         timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"         int,
    "UpdatedAt"         timestamp(3),
    "UpdatedBy"         int,
    CONSTRAINT "PK_PurchaseRequisitions" PRIMARY KEY ("RequisitionId"),
    CONSTRAINT "UQ_PurchaseRequisitions_Number" UNIQUE ("RequisitionNumber"),
    CONSTRAINT "CK_PurchaseRequisitions_Status" CHECK ("Status" IN ('Cancelled','Converted','Partial','Open','Draft'))
);

CREATE INDEX "IX_PurchaseRequisitions_Status"
    ON "PurchaseRequisitions" ("Status", "RequisitionDate") INCLUDE ("RequisitionNumber");

CREATE TABLE "PurchaseRequisitionDetails"
(
    "RequisitionDetailId" bigint        GENERATED BY DEFAULT AS IDENTITY,
    "RequisitionId"       bigint        NOT NULL,
    "LineNumber"          int           NOT NULL,
    "ItemId"              int           NOT NULL,
    "RequiredQty"         numeric(18,3) NOT NULL,
    "OrderedQty"          numeric(18,3) NOT NULL DEFAULT 0,
    "PendingQty"          numeric(19,3) GENERATED ALWAYS AS ("RequiredQty" - "OrderedQty") STORED,
    "UnitId"              int           NOT NULL,
    "ExpectedDate"        date,
    "EstimatedRate"       numeric(18,4) NOT NULL DEFAULT 0,
    "Remarks"             varchar(300),
    CONSTRAINT "PK_PurchaseRequisitionDetails" PRIMARY KEY ("RequisitionDetailId"),
    CONSTRAINT "CK_PurchaseRequisitionDetails_Qty" CHECK ("RequiredQty" > 0 AND "OrderedQty" >= 0 AND "OrderedQty" <= "RequiredQty")
);

CREATE INDEX "IX_PurchaseRequisitionDetails_ItemId"
    ON "PurchaseRequisitionDetails" ("ItemId") INCLUDE ("RequisitionId", "PendingQty");
CREATE INDEX "IX_PurchaseRequisitionDetails_ReqId"
    ON "PurchaseRequisitionDetails" ("RequisitionId", "LineNumber");

CREATE TABLE "PurchaseOrders"
(
    "PurchaseOrderId" bigint        GENERATED BY DEFAULT AS IDENTITY,
    "OrderNumber"     varchar(30)   NOT NULL,
    "OrderDate"       date          NOT NULL,
    "ExpectedDate"    date,
    "SupplierId"      int           NOT NULL,
    "LocationId"      int           NOT NULL,
    "Remarks"         varchar(500),
    "TotalQty"        numeric(18,3) NOT NULL DEFAULT 0,
    "EstimatedValue"  numeric(18,2) NOT NULL DEFAULT 0,
    "Status"          varchar(15)   NOT NULL DEFAULT 'Draft',
    "FinancialYearId" int,
    "CreatedAt"       timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"       int,
    "UpdatedAt"       timestamp(3),
    "UpdatedBy"       int,
    "VoucherId"       int,
    CONSTRAINT "PK_PurchaseOrders" PRIMARY KEY ("PurchaseOrderId"),
    CONSTRAINT "UQ_PurchaseOrders_Number" UNIQUE ("OrderNumber"),
    CONSTRAINT "CK_PurchaseOrders_Status" CHECK ("Status" IN ('Cancelled','Received','Partial','Open','Draft'))
);

CREATE INDEX "IX_PurchaseOrders_Status"
    ON "PurchaseOrders" ("Status", "ExpectedDate") INCLUDE ("OrderNumber", "SupplierId");
CREATE INDEX "IX_PurchaseOrders_Supplier_Date"
    ON "PurchaseOrders" ("SupplierId", "OrderDate") INCLUDE ("OrderNumber", "Status", "EstimatedValue");

CREATE TABLE "PurchaseOrderDetails"
(
    "PurchaseOrderDetailId" bigint        GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseOrderId"       bigint        NOT NULL,
    "LineNumber"            int           NOT NULL,
    "ItemId"                int           NOT NULL,
    "OrderedQty"            numeric(18,3) NOT NULL,
    "ReceivedQty"           numeric(18,3) NOT NULL DEFAULT 0,
    "PendingQty"            numeric(19,3) GENERATED ALWAYS AS ("OrderedQty" - "ReceivedQty") STORED,
    "UnitId"                int           NOT NULL,
    "Rate"                  numeric(18,4) NOT NULL DEFAULT 0,
    "EstimatedAmount"       numeric(18,2) GENERATED ALWAYS AS (CAST("OrderedQty" * "Rate" AS numeric(18,2))) STORED,
    "Remarks"               varchar(300),
    "RequisitionDetailId"   bigint,
    "NoOfPacks"             numeric(18,3) NOT NULL DEFAULT 0,
    "QtyPerPack"            numeric(18,3) NOT NULL DEFAULT 0,
    "RequiredQty"           numeric(18,3),
    "ItemRemark"            varchar(300),
    CONSTRAINT "PK_PurchaseOrderDetails" PRIMARY KEY ("PurchaseOrderDetailId"),
    CONSTRAINT "CK_PurchaseOrderDetails_Qty" CHECK ("OrderedQty" > 0 AND "ReceivedQty" >= 0 AND "ReceivedQty" <= "OrderedQty")
);

CREATE INDEX "IX_PurchaseOrderDetails_OrderId"
    ON "PurchaseOrderDetails" ("PurchaseOrderId", "LineNumber");
CREATE INDEX "IX_PurchaseOrderDetails_ProductId"
    ON "PurchaseOrderDetails" ("ItemId") INCLUDE ("PurchaseOrderId", "PendingQty");

CREATE TABLE "Purchases"
(
    "PurchaseId"            bigint        GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseNumber"        varchar(30)   NOT NULL,
    "PurchaseDate"          date          NOT NULL,
    "SupplierId"            int           NOT NULL,
    "SupplierInvoiceNumber" varchar(50),
    "SupplierInvoiceDate"   date,
    "PurchaseOrderId"       bigint,
    "LocationId"            int           NOT NULL,
    "IsInterState"          boolean       NOT NULL DEFAULT false,
    "SupplierStateId"       int,
    "GrossAmount"           numeric(18,2) NOT NULL DEFAULT 0,
    "DiscountAmount"        numeric(18,2) NOT NULL DEFAULT 0,
    "TaxableAmount"         numeric(18,2) NOT NULL DEFAULT 0,
    "CgstAmount"            numeric(18,2) NOT NULL DEFAULT 0,
    "SgstAmount"            numeric(18,2) NOT NULL DEFAULT 0,
    "IgstAmount"            numeric(18,2) NOT NULL DEFAULT 0,
    "CessAmount"            numeric(18,2) NOT NULL DEFAULT 0,
    "FreightCharges"        numeric(18,2) NOT NULL DEFAULT 0,
    "OtherCharges"          numeric(18,2) NOT NULL DEFAULT 0,
    "RoundOff"              numeric(18,2) NOT NULL DEFAULT 0,
    "GrandTotal"            numeric(25,2) GENERATED ALWAYS AS ("TaxableAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount" + "FreightCharges" + "OtherCharges" + "RoundOff") STORED,
    "PaidAmount"            numeric(18,2) NOT NULL DEFAULT 0,
    "BalanceAmount"         numeric(26,2) GENERATED ALWAYS AS (("TaxableAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount" + "FreightCharges" + "OtherCharges" + "RoundOff") - "PaidAmount") STORED,
    "PaymentStatus"         varchar(7)    GENERATED ALWAYS AS (
        CASE WHEN "PaidAmount" <= 0 THEN 'Unpaid'
             WHEN "PaidAmount" >= ("TaxableAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount" + "FreightCharges" + "OtherCharges" + "RoundOff") THEN 'Paid'
             ELSE 'Partial' END) STORED,
    "DueDate"               date,
    "Status"                varchar(15)   NOT NULL DEFAULT 'Draft',
    "PostedAt"              timestamp(3),
    "PostedBy"              int,
    "CancelledAt"           timestamp(3),
    "CancelledBy"           int,
    "CancelReason"          varchar(300),
    "Remarks"               varchar(500),
    "FinancialYearId"       int,
    "CreatedAt"             timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"             int,
    "UpdatedAt"             timestamp(3),
    "UpdatedBy"             int,
    "VoucherId"             int,
    "WarehouseId"           int,
    CONSTRAINT "PK_Purchases" PRIMARY KEY ("PurchaseId"),
    CONSTRAINT "UQ_Purchases_PurchaseNumber" UNIQUE ("PurchaseNumber"),
    CONSTRAINT "CK_Purchases_Status" CHECK ("Status" IN ('Cancelled','Posted','Draft')),
    CONSTRAINT "CK_Purchases_Amounts" CHECK ("GrossAmount" >= 0 AND "DiscountAmount" >= 0 AND "TaxableAmount" >= 0 AND "CgstAmount" >= 0 AND "SgstAmount" >= 0 AND "IgstAmount" >= 0 AND "CessAmount" >= 0 AND "PaidAmount" >= 0),
    CONSTRAINT "CK_Purchases_TaxMode" CHECK (("IsInterState" = true AND "CgstAmount" = 0 AND "SgstAmount" = 0) OR ("IsInterState" = false AND "IgstAmount" = 0))
);

CREATE INDEX "IX_Purchases_Outstanding"
    ON "Purchases" ("SupplierId", "DueDate")
    INCLUDE ("PurchaseNumber", "PurchaseDate", "GrandTotal", "PaidAmount", "BalanceAmount") WHERE "Status" = 'Posted';
CREATE INDEX "IX_Purchases_PurchaseDate"
    ON "Purchases" ("PurchaseDate")
    INCLUDE ("SupplierId", "PurchaseNumber", "TaxableAmount", "CgstAmount", "SgstAmount", "IgstAmount", "GrandTotal", "Status");
CREATE INDEX "IX_Purchases_Supplier_Date"
    ON "Purchases" ("SupplierId", "PurchaseDate")
    INCLUDE ("PurchaseNumber", "GrandTotal", "PaidAmount", "BalanceAmount", "Status");
CREATE UNIQUE INDEX "UQ_Purchases_Supplier_InvoiceNumber"
    ON "Purchases" ("SupplierId", "SupplierInvoiceNumber")
    WHERE "SupplierInvoiceNumber" IS NOT NULL AND "Status" <> 'Cancelled';

CREATE TABLE "PurchaseDetails"
(
    "PurchaseDetailId"  bigint        GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseId"        bigint        NOT NULL,
    "LineNumber"        int           NOT NULL,
    "ItemId"            int           NOT NULL,
    -- The PO line this receipt fills (nullable; see SQL Server script for why).
    "PurchaseOrderDetailId" bigint,
    "BatchId"           bigint,
    "BatchNumber"       varchar(50),
    "ManufacturingDate" date,
    "ExpiryDate"        date,
    "Quantity"          numeric(18,3) NOT NULL,
    "FreeQuantity"      numeric(18,3) NOT NULL DEFAULT 0,
    "TotalQuantity"     numeric(19,3) GENERATED ALWAYS AS ("Quantity" + "FreeQuantity") STORED,
    "UnitId"            int           NOT NULL,
    "Rate"              numeric(18,4) NOT NULL,
    "GrossAmount"       numeric(18,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2))) STORED,
    "DiscountPercent"   numeric(6,3)  NOT NULL DEFAULT 0,
    "DiscountAmount"    numeric(18,2) NOT NULL DEFAULT 0,
    "TaxableAmount"     numeric(19,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2)) - "DiscountAmount") STORED,
    "GstPercent"        numeric(6,3)  NOT NULL DEFAULT 0,
    "CgstAmount"        numeric(18,2) NOT NULL DEFAULT 0,
    "SgstAmount"        numeric(18,2) NOT NULL DEFAULT 0,
    "IgstAmount"        numeric(18,2) NOT NULL DEFAULT 0,
    "CessAmount"        numeric(18,2) NOT NULL DEFAULT 0,
    "LineTotal"         numeric(23,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2)) - "DiscountAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount") STORED,
    "LandedRate"        numeric(18,4) NOT NULL DEFAULT 0,
    "Mrp"               numeric(18,4) NOT NULL DEFAULT 0,
    "SellingRate"       numeric(18,4) NOT NULL DEFAULT 0,
    "HsnCode"           varchar(10),
    "Remarks"           varchar(300),
    CONSTRAINT "PK_PurchaseDetails" PRIMARY KEY ("PurchaseDetailId"),
    CONSTRAINT "CK_PurchaseDetails_Quantity" CHECK ("Quantity" > 0 AND "FreeQuantity" >= 0),
    CONSTRAINT "CK_PurchaseDetails_Rate" CHECK ("Rate" >= 0 AND "LandedRate" >= 0),
    CONSTRAINT "CK_PurchaseDetails_Discount" CHECK ("DiscountAmount" >= 0 AND "DiscountPercent" >= 0 AND "DiscountPercent" <= 100)
);

CREATE INDEX "IX_PurchaseDetails_BatchId"
    ON "PurchaseDetails" ("BatchId") INCLUDE ("PurchaseId", "ItemId", "Quantity", "LandedRate");
CREATE INDEX "IX_PurchaseDetails_ProductId"
    ON "PurchaseDetails" ("ItemId") INCLUDE ("PurchaseId", "BatchId", "Quantity", "FreeQuantity", "Rate", "LandedRate", "ExpiryDate");
CREATE INDEX "IX_PurchaseDetails_PurchaseId"
    ON "PurchaseDetails" ("PurchaseId", "LineNumber");

CREATE TABLE "PurchaseReturns"
(
    "PurchaseReturnId" bigint        GENERATED BY DEFAULT AS IDENTITY,
    "ReturnNumber"     varchar(30)   NOT NULL,
    "ReturnDate"       date          NOT NULL,
    "SupplierId"       int           NOT NULL,
    "PurchaseId"       bigint,
    "LocationId"       int           NOT NULL,
    "DebitNoteNumber"  varchar(50),
    "ReturnReason"     varchar(300),
    "IsInterState"     boolean       NOT NULL DEFAULT false,
    "GrossAmount"      numeric(18,2) NOT NULL DEFAULT 0,
    "DiscountAmount"   numeric(18,2) NOT NULL DEFAULT 0,
    "TaxableAmount"    numeric(18,2) NOT NULL DEFAULT 0,
    "CgstAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "SgstAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "IgstAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "CessAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "RoundOff"         numeric(18,2) NOT NULL DEFAULT 0,
    "GrandTotal"       numeric(23,2) GENERATED ALWAYS AS ("TaxableAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount" + "RoundOff") STORED,
    "Status"           varchar(15)   NOT NULL DEFAULT 'Draft',
    "PostedAt"         timestamp(3),
    "PostedBy"         int,
    "Remarks"          varchar(500),
    "FinancialYearId"  int,
    "CreatedAt"        timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"        int,
    "UpdatedAt"        timestamp(3),
    "UpdatedBy"        int,
    CONSTRAINT "PK_PurchaseReturns" PRIMARY KEY ("PurchaseReturnId"),
    CONSTRAINT "UQ_PurchaseReturns_Number" UNIQUE ("ReturnNumber"),
    CONSTRAINT "CK_PurchaseReturns_Status" CHECK ("Status" IN ('Cancelled','Posted','Draft'))
);

CREATE INDEX "IX_PurchaseReturns_Date"
    ON "PurchaseReturns" ("ReturnDate") INCLUDE ("SupplierId", "TaxableAmount", "GrandTotal", "Status");
CREATE INDEX "IX_PurchaseReturns_Supplier_Date"
    ON "PurchaseReturns" ("SupplierId", "ReturnDate") INCLUDE ("ReturnNumber", "GrandTotal", "Status");

CREATE TABLE "PurchaseReturnDetails"
(
    "PurchaseReturnDetailId" bigint        GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseReturnId"       bigint        NOT NULL,
    "LineNumber"             int           NOT NULL,
    "ItemId"                 int           NOT NULL,
    "BatchId"                bigint        NOT NULL,
    "PurchaseDetailId"       bigint,
    "Quantity"               numeric(18,3) NOT NULL,
    "UnitId"                 int           NOT NULL,
    "Rate"                   numeric(18,4) NOT NULL,
    "GrossAmount"            numeric(18,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2))) STORED,
    "DiscountAmount"         numeric(18,2) NOT NULL DEFAULT 0,
    "TaxableAmount"          numeric(19,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2)) - "DiscountAmount") STORED,
    "GstPercent"             numeric(6,3)  NOT NULL DEFAULT 0,
    "CgstAmount"             numeric(18,2) NOT NULL DEFAULT 0,
    "SgstAmount"             numeric(18,2) NOT NULL DEFAULT 0,
    "IgstAmount"             numeric(18,2) NOT NULL DEFAULT 0,
    "CessAmount"             numeric(18,2) NOT NULL DEFAULT 0,
    "LineTotal"              numeric(23,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2)) - "DiscountAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount") STORED,
    "ReturnReason"           varchar(300),
    CONSTRAINT "PK_PurchaseReturnDetails" PRIMARY KEY ("PurchaseReturnDetailId"),
    CONSTRAINT "CK_PurchaseReturnDetails_Quantity" CHECK ("Quantity" > 0)
);

CREATE INDEX "IX_PurchaseReturnDetails_ProductId"
    ON "PurchaseReturnDetails" ("ItemId") INCLUDE ("BatchId", "Quantity", "Rate");
CREATE INDEX "IX_PurchaseReturnDetails_ReturnId"
    ON "PurchaseReturnDetails" ("PurchaseReturnId", "LineNumber");
