/*==============================================================================
  AgriERP  |  07_sales.sql   (PostgreSQL)
  ------------------------------------------------------------------------------
  Sales invoices, lines, receipts and sales returns. PostgreSQL parallel of
  database/scripts/07_Sales.sql (final state). FKs in 80_foreign_keys.sql,
  ROWVERSION dropped, persisted totals -> GENERATED ... STORED.
==============================================================================*/

CREATE TABLE "Sales"
(
    "SaleId"               bigint        GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceNumber"        varchar(30)   NOT NULL,
    "InvoiceDate"          date          NOT NULL,
    "InvoiceTime"          time(0),
    "CustomerId"           int,
    "WalkInCustomerName"   varchar(150),
    "WalkInMobile"         varchar(15),
    "SaleType"             varchar(15)   NOT NULL DEFAULT 'Retail',
    "PaymentType"          varchar(10)   NOT NULL DEFAULT 'Cash',
    "LocationId"           int           NOT NULL,
    "SalesmanId"           int,
    "IsInterState"         boolean       NOT NULL DEFAULT false,
    "PlaceOfSupplyStateId" int,
    "GrossAmount"          numeric(18,2) NOT NULL DEFAULT 0,
    "DiscountAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "TaxableAmount"        numeric(18,2) NOT NULL DEFAULT 0,
    "CgstAmount"           numeric(18,2) NOT NULL DEFAULT 0,
    "SgstAmount"           numeric(18,2) NOT NULL DEFAULT 0,
    "IgstAmount"           numeric(18,2) NOT NULL DEFAULT 0,
    "CessAmount"           numeric(18,2) NOT NULL DEFAULT 0,
    "OtherCharges"         numeric(18,2) NOT NULL DEFAULT 0,
    "RoundOff"             numeric(18,2) NOT NULL DEFAULT 0,
    "GrandTotal"           numeric(24,2) GENERATED ALWAYS AS ("TaxableAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount" + "OtherCharges" + "RoundOff") STORED,
    "TotalCostAmount"      numeric(18,2) NOT NULL DEFAULT 0,
    "GrossProfit"          numeric(19,2) GENERATED ALWAYS AS ("TaxableAmount" - "TotalCostAmount") STORED,
    "ReceivedAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "BalanceAmount"        numeric(25,2) GENERATED ALWAYS AS (("TaxableAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount" + "OtherCharges" + "RoundOff") - "ReceivedAmount") STORED,
    "PaymentStatus"        varchar(7)    GENERATED ALWAYS AS (
        CASE WHEN "ReceivedAmount" <= 0 THEN 'Unpaid'
             WHEN "ReceivedAmount" >= ("TaxableAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount" + "OtherCharges" + "RoundOff") THEN 'Paid'
             ELSE 'Partial' END) STORED,
    "DueDate"              date,
    "Status"              varchar(15)   NOT NULL DEFAULT 'Draft',
    "PostedAt"            timestamp(3),
    "PostedBy"           int,
    "CancelledAt"        timestamp(3),
    "CancelledBy"        int,
    "CancelReason"       varchar(300),
    "PrintCount"         int           NOT NULL DEFAULT 0,
    "Remarks"            varchar(500),
    "FinancialYearId"    int,
    "CreatedAt"          timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"          int,
    "UpdatedAt"          timestamp(3),
    "UpdatedBy"          int,
    CONSTRAINT "PK_Sales" PRIMARY KEY ("SaleId"),
    CONSTRAINT "UQ_Sales_InvoiceNumber" UNIQUE ("InvoiceNumber"),
    CONSTRAINT "CK_Sales_SaleType" CHECK ("SaleType" IN ('Dealer','Wholesale','Retail')),
    CONSTRAINT "CK_Sales_PaymentType" CHECK ("PaymentType" IN ('Credit','Cash')),
    CONSTRAINT "CK_Sales_Status" CHECK ("Status" IN ('Cancelled','Posted','Draft')),
    CONSTRAINT "CK_Sales_CreditNeedsCustomer" CHECK ("PaymentType" = 'Cash' OR "CustomerId" IS NOT NULL),
    CONSTRAINT "CK_Sales_Amounts" CHECK ("GrossAmount" >= 0 AND "DiscountAmount" >= 0 AND "TaxableAmount" >= 0 AND "CgstAmount" >= 0 AND "SgstAmount" >= 0 AND "IgstAmount" >= 0 AND "CessAmount" >= 0 AND "ReceivedAmount" >= 0),
    CONSTRAINT "CK_Sales_TaxMode" CHECK (("IsInterState" = true AND "CgstAmount" = 0 AND "SgstAmount" = 0) OR ("IsInterState" = false AND "IgstAmount" = 0))
);

CREATE INDEX "IX_Sales_Customer_Date"
    ON "Sales" ("CustomerId", "InvoiceDate")
    INCLUDE ("InvoiceNumber", "GrandTotal", "ReceivedAmount", "BalanceAmount", "Status") WHERE "CustomerId" IS NOT NULL;
CREATE INDEX "IX_Sales_InvoiceDate"
    ON "Sales" ("InvoiceDate")
    INCLUDE ("InvoiceNumber", "CustomerId", "TaxableAmount", "CgstAmount", "SgstAmount", "IgstAmount", "GrandTotal", "TotalCostAmount", "GrossProfit", "Status", "PaymentType");
CREATE INDEX "IX_Sales_Outstanding"
    ON "Sales" ("CustomerId", "DueDate")
    INCLUDE ("InvoiceNumber", "InvoiceDate", "GrandTotal", "ReceivedAmount", "BalanceAmount") WHERE "Status" = 'Posted' AND "CustomerId" IS NOT NULL;
CREATE INDEX "IX_Sales_WalkInMobile"
    ON "Sales" ("WalkInMobile") INCLUDE ("InvoiceNumber", "InvoiceDate", "GrandTotal") WHERE "WalkInMobile" IS NOT NULL;

CREATE TABLE "SalesDetails"
(
    "SalesDetailId"   bigint        GENERATED BY DEFAULT AS IDENTITY,
    "SaleId"          bigint        NOT NULL,
    "LineNumber"      int           NOT NULL,
    "ItemId"          int           NOT NULL,
    "BatchId"         bigint        NOT NULL,
    "BatchNumber"     varchar(50),
    "ExpiryDate"      date,
    "Quantity"        numeric(18,3) NOT NULL,
    "FreeQuantity"    numeric(18,3) NOT NULL DEFAULT 0,
    "TotalQuantity"   numeric(19,3) GENERATED ALWAYS AS ("Quantity" + "FreeQuantity") STORED,
    "UnitId"          int           NOT NULL,
    "Mrp"             numeric(18,4) NOT NULL DEFAULT 0,
    "Rate"            numeric(18,4) NOT NULL,
    "GrossAmount"     numeric(18,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2))) STORED,
    "DiscountPercent" numeric(6,3)  NOT NULL DEFAULT 0,
    "DiscountAmount"  numeric(18,2) NOT NULL DEFAULT 0,
    "TaxableAmount"   numeric(19,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2)) - "DiscountAmount") STORED,
    "GstPercent"      numeric(6,3)  NOT NULL DEFAULT 0,
    "CgstAmount"      numeric(18,2) NOT NULL DEFAULT 0,
    "SgstAmount"      numeric(18,2) NOT NULL DEFAULT 0,
    "IgstAmount"      numeric(18,2) NOT NULL DEFAULT 0,
    "CessAmount"      numeric(18,2) NOT NULL DEFAULT 0,
    "LineTotal"       numeric(23,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2)) - "DiscountAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount") STORED,
    "CostRate"        numeric(18,4) NOT NULL DEFAULT 0,
    "CostAmount"      numeric(18,2) GENERATED ALWAYS AS (CAST(("Quantity" + "FreeQuantity") * "CostRate" AS numeric(18,2))) STORED,
    "LineProfit"      numeric(20,2) GENERATED ALWAYS AS ((CAST("Quantity" * "Rate" AS numeric(18,2)) - "DiscountAmount") - CAST(("Quantity" + "FreeQuantity") * "CostRate" AS numeric(18,2))) STORED,
    "HsnCode"         varchar(10),
    "Remarks"         varchar(300),
    CONSTRAINT "PK_SalesDetails" PRIMARY KEY ("SalesDetailId"),
    CONSTRAINT "CK_SalesDetails_Quantity" CHECK ("Quantity" > 0 AND "FreeQuantity" >= 0),
    CONSTRAINT "CK_SalesDetails_Rate" CHECK ("Rate" >= 0 AND "CostRate" >= 0),
    CONSTRAINT "CK_SalesDetails_Discount" CHECK ("DiscountAmount" >= 0 AND "DiscountPercent" >= 0 AND "DiscountPercent" <= 100)
);

CREATE INDEX "IX_SalesDetails_BatchId"
    ON "SalesDetails" ("BatchId") INCLUDE ("SaleId", "ItemId", "Quantity", "CostRate");
CREATE INDEX "IX_SalesDetails_ProductId"
    ON "SalesDetails" ("ItemId") INCLUDE ("SaleId", "BatchId", "Quantity", "TotalQuantity", "Rate", "TaxableAmount", "CostAmount", "LineProfit");
CREATE INDEX "IX_SalesDetails_SaleId"
    ON "SalesDetails" ("SaleId", "LineNumber");

CREATE TABLE "SalePayments"
(
    "SalePaymentId"   bigint        GENERATED BY DEFAULT AS IDENTITY,
    "SaleId"          bigint        NOT NULL,
    "PaymentModeId"   int           NOT NULL,
    "Amount"          numeric(18,2) NOT NULL,
    "ReferenceNumber" varchar(60),
    "BankName"        varchar(120),
    "ChequeDate"      date,
    "Remarks"         varchar(300),
    "CreatedAt"       timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"       int,
    CONSTRAINT "PK_SalePayments" PRIMARY KEY ("SalePaymentId"),
    CONSTRAINT "CK_SalePayments_Amount" CHECK ("Amount" > 0)
);

CREATE INDEX "IX_SalePayments_ModeId"
    ON "SalePayments" ("PaymentModeId", "CreatedAt") INCLUDE ("Amount", "SaleId");
CREATE INDEX "IX_SalePayments_SaleId"
    ON "SalePayments" ("SaleId") INCLUDE ("PaymentModeId", "Amount");

CREATE TABLE "SalesReturns"
(
    "SalesReturnId"    bigint        GENERATED BY DEFAULT AS IDENTITY,
    "ReturnNumber"     varchar(30)   NOT NULL,
    "ReturnDate"       date          NOT NULL,
    "CustomerId"       int,
    "SaleId"           bigint,
    "LocationId"       int           NOT NULL,
    "CreditNoteNumber" varchar(50),
    "ReturnReason"     varchar(300),
    "IsInterState"     boolean       NOT NULL DEFAULT false,
    "GrossAmount"      numeric(18,2) NOT NULL DEFAULT 0,
    "DiscountAmount"   numeric(18,2) NOT NULL DEFAULT 0,
    "TaxableAmount"    numeric(18,2) NOT NULL DEFAULT 0,
    "CgstAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "SgstAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "IgstAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "CessAmount"       numeric(18,2) NOT NULL DEFAULT 0,
    "RoundOff"         numeric(18,2) NOT NULL DEFAULT 0,
    "GrandTotal"       numeric(23,2) GENERATED ALWAYS AS ("TaxableAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount" + "RoundOff") STORED,
    "TotalCostAmount"  numeric(18,2) NOT NULL DEFAULT 0,
    "RefundMode"       varchar(15)   NOT NULL DEFAULT 'Adjust',
    "RefundedAmount"   numeric(18,2) NOT NULL DEFAULT 0,
    "Status"           varchar(15)   NOT NULL DEFAULT 'Draft',
    "PostedAt"         timestamp(3),
    "PostedBy"         int,
    "Remarks"          varchar(500),
    "FinancialYearId"  int,
    "CreatedAt"        timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"        int,
    "UpdatedAt"        timestamp(3),
    "UpdatedBy"        int,
    CONSTRAINT "PK_SalesReturns" PRIMARY KEY ("SalesReturnId"),
    CONSTRAINT "UQ_SalesReturns_Number" UNIQUE ("ReturnNumber"),
    CONSTRAINT "CK_SalesReturns_Status" CHECK ("Status" IN ('Cancelled','Posted','Draft')),
    CONSTRAINT "CK_SalesReturns_RefundMode" CHECK ("RefundMode" IN ('Replacement','Bank','Adjust','Cash'))
);

CREATE INDEX "IX_SalesReturns_Customer"
    ON "SalesReturns" ("CustomerId", "ReturnDate") INCLUDE ("ReturnNumber", "GrandTotal", "Status") WHERE "CustomerId" IS NOT NULL;
CREATE INDEX "IX_SalesReturns_Date"
    ON "SalesReturns" ("ReturnDate") INCLUDE ("CustomerId", "TaxableAmount", "GrandTotal", "Status");
CREATE INDEX "IX_SalesReturns_SaleId"
    ON "SalesReturns" ("SaleId") WHERE "SaleId" IS NOT NULL;

CREATE TABLE "SalesReturnDetails"
(
    "SalesReturnDetailId" bigint        GENERATED BY DEFAULT AS IDENTITY,
    "SalesReturnId"       bigint        NOT NULL,
    "LineNumber"          int           NOT NULL,
    "ItemId"              int           NOT NULL,
    "BatchId"             bigint        NOT NULL,
    "SalesDetailId"       bigint,
    "Quantity"            numeric(18,3) NOT NULL,
    "UnitId"              int           NOT NULL,
    "Rate"                numeric(18,4) NOT NULL,
    "GrossAmount"         numeric(18,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2))) STORED,
    "DiscountAmount"      numeric(18,2) NOT NULL DEFAULT 0,
    "TaxableAmount"       numeric(19,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2)) - "DiscountAmount") STORED,
    "GstPercent"          numeric(6,3)  NOT NULL DEFAULT 0,
    "CgstAmount"          numeric(18,2) NOT NULL DEFAULT 0,
    "SgstAmount"          numeric(18,2) NOT NULL DEFAULT 0,
    "IgstAmount"          numeric(18,2) NOT NULL DEFAULT 0,
    "CessAmount"          numeric(18,2) NOT NULL DEFAULT 0,
    "LineTotal"           numeric(23,2) GENERATED ALWAYS AS (CAST("Quantity" * "Rate" AS numeric(18,2)) - "DiscountAmount" + "CgstAmount" + "SgstAmount" + "IgstAmount" + "CessAmount") STORED,
    "CostRate"            numeric(18,4) NOT NULL DEFAULT 0,
    "CostAmount"          numeric(18,2) GENERATED ALWAYS AS (CAST("Quantity" * "CostRate" AS numeric(18,2))) STORED,
    "IsSaleable"          boolean       NOT NULL DEFAULT true,
    "ReturnReason"        varchar(300),
    CONSTRAINT "PK_SalesReturnDetails" PRIMARY KEY ("SalesReturnDetailId"),
    CONSTRAINT "CK_SalesReturnDetails_Quantity" CHECK ("Quantity" > 0)
);

CREATE INDEX "IX_SalesReturnDetails_ProductId"
    ON "SalesReturnDetails" ("ItemId") INCLUDE ("BatchId", "Quantity", "Rate", "CostRate");
CREATE INDEX "IX_SalesReturnDetails_ReturnId"
    ON "SalesReturnDetails" ("SalesReturnId", "LineNumber");
