/*==============================================================================
  AgriERP  |  08_finance.sql   (PostgreSQL)
  ------------------------------------------------------------------------------
  Payment modes, party payments/receipts, their allocations, expense categories
  and expenses. PostgreSQL parallel of database/scripts/08_Finance.sql (+ 29).
  FKs in 80_foreign_keys.sql, ROWVERSION dropped.
==============================================================================*/

CREATE TABLE "PaymentModes"
(
    "PaymentModeId"     int         GENERATED BY DEFAULT AS IDENTITY,
    "ModeCode"          varchar(20) NOT NULL,
    "ModeName"          varchar(50) NOT NULL,
    "RequiresReference" boolean     NOT NULL DEFAULT false,
    "IsBankMode"        boolean     NOT NULL DEFAULT false,
    "DisplayOrder"      int         NOT NULL DEFAULT 0,
    "IsActive"          boolean     NOT NULL DEFAULT true,
    CONSTRAINT "PK_PaymentModes" PRIMARY KEY ("PaymentModeId"),
    CONSTRAINT "UQ_PaymentModes_Code" UNIQUE ("ModeCode")
);

CREATE TABLE "Payments"
(
    "PaymentId"         bigint        GENERATED BY DEFAULT AS IDENTITY,
    "VoucherNumber"     varchar(30)   NOT NULL,
    "PaymentDate"       date          NOT NULL,
    "PartyType"         varchar(10)   NOT NULL,
    "CustomerId"        int,
    "SupplierId"        int,
    "PaymentType"       varchar(10)   NOT NULL,
    "PaymentModeId"     int           NOT NULL,
    "Amount"            numeric(18,2) NOT NULL,
    "AllocatedAmount"   numeric(18,2) NOT NULL DEFAULT 0,
    "UnallocatedAmount" numeric(19,2) GENERATED ALWAYS AS ("Amount" - "AllocatedAmount") STORED,
    "ReferenceNumber"   varchar(60),
    "BankName"          varchar(120),
    "ChequeDate"        date,
    "ClearanceStatus"   varchar(15)   NOT NULL DEFAULT 'Cleared',
    "ClearedDate"       date,
    "Remarks"           varchar(500),
    "Status"            varchar(15)   NOT NULL DEFAULT 'Posted',
    "CancelledAt"       timestamp(3),
    "CancelledBy"       int,
    "CancelReason"      varchar(300),
    "FinancialYearId"   int,
    "CreatedAt"         timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"         int,
    "UpdatedAt"         timestamp(3),
    "UpdatedBy"         int,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("PaymentId"),
    CONSTRAINT "UQ_Payments_VoucherNumber" UNIQUE ("VoucherNumber"),
    CONSTRAINT "CK_Payments_PartyType" CHECK ("PartyType" IN ('Supplier','Customer')),
    CONSTRAINT "CK_Payments_PaymentType" CHECK ("PaymentType" IN ('Payment','Receipt')),
    CONSTRAINT "CK_Payments_Status" CHECK ("Status" IN ('Cancelled','Posted')),
    CONSTRAINT "CK_Payments_Clearance" CHECK ("ClearanceStatus" IN ('Bounced','Cleared','Pending')),
    CONSTRAINT "CK_Payments_Party" CHECK (
        ("PartyType" = 'Customer' AND "CustomerId" IS NOT NULL AND "SupplierId" IS NULL)
        OR ("PartyType" = 'Supplier' AND "SupplierId" IS NOT NULL AND "CustomerId" IS NULL)),
    CONSTRAINT "CK_Payments_Amount" CHECK ("Amount" > 0),
    CONSTRAINT "CK_Payments_Allocated" CHECK ("AllocatedAmount" >= 0 AND "AllocatedAmount" <= "Amount")
);

CREATE INDEX "IX_Payments_Customer_Date"
    ON "Payments" ("CustomerId", "PaymentDate")
    INCLUDE ("VoucherNumber", "Amount", "AllocatedAmount", "UnallocatedAmount", "PaymentType", "Status") WHERE "CustomerId" IS NOT NULL;
CREATE INDEX "IX_Payments_Date"
    ON "Payments" ("PaymentDate") INCLUDE ("PaymentModeId", "PaymentType", "Amount", "Status");
CREATE INDEX "IX_Payments_Pending"
    ON "Payments" ("ClearanceStatus", "ChequeDate")
    INCLUDE ("VoucherNumber", "Amount", "CustomerId", "SupplierId") WHERE "ClearanceStatus" = 'Pending';
CREATE INDEX "IX_Payments_Supplier_Date"
    ON "Payments" ("SupplierId", "PaymentDate")
    INCLUDE ("VoucherNumber", "Amount", "AllocatedAmount", "UnallocatedAmount", "PaymentType", "Status") WHERE "SupplierId" IS NOT NULL;

CREATE TABLE "PaymentAllocations"
(
    "PaymentAllocationId" bigint        GENERATED BY DEFAULT AS IDENTITY,
    "PaymentId"           bigint        NOT NULL,
    "ReferenceType"       varchar(20)   NOT NULL,
    "ReferenceId"         bigint        NOT NULL,
    "ReferenceNumber"     varchar(30),
    "AllocatedAmount"     numeric(18,2) NOT NULL,
    "AllocatedAt"         timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "AllocatedBy"         int,
    CONSTRAINT "PK_PaymentAllocations" PRIMARY KEY ("PaymentAllocationId"),
    CONSTRAINT "UQ_PaymentAllocations_Payment_Reference" UNIQUE ("PaymentId", "ReferenceType", "ReferenceId"),
    CONSTRAINT "CK_PaymentAllocations_ReferenceType" CHECK ("ReferenceType" IN ('PurchaseReturn','SalesReturn','Purchase','Sale')),
    CONSTRAINT "CK_PaymentAllocations_Amount" CHECK ("AllocatedAmount" > 0)
);

CREATE INDEX "IX_PaymentAllocations_Reference"
    ON "PaymentAllocations" ("ReferenceType", "ReferenceId") INCLUDE ("PaymentId", "AllocatedAmount", "AllocatedAt");

CREATE TABLE "ExpenseCategories"
(
    "ExpenseCategoryId" int          GENERATED BY DEFAULT AS IDENTITY,
    "CategoryCode"      varchar(20)  NOT NULL,
    "CategoryName"      varchar(100) NOT NULL,
    "Description"       varchar(300),
    "IsActive"          boolean      NOT NULL DEFAULT true,
    "IsDeleted"         boolean      NOT NULL DEFAULT false,
    "CreatedAt"         timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"         int,
    "UpdatedAt"         timestamp(3),
    "UpdatedBy"         int,
    CONSTRAINT "PK_ExpenseCategories" PRIMARY KEY ("ExpenseCategoryId")
);

CREATE UNIQUE INDEX "UQ_ExpenseCategories_Code"
    ON "ExpenseCategories" ("CategoryCode") WHERE "IsDeleted" = false;

CREATE TABLE "Expenses"
(
    "ExpenseId"         bigint        GENERATED BY DEFAULT AS IDENTITY,
    "VoucherNumber"     varchar(30)   NOT NULL,
    "ExpenseDate"       date          NOT NULL,
    "ExpenseCategoryId" int           NOT NULL,
    "PaymentModeId"     int           NOT NULL,
    "PaidTo"            varchar(150),
    "Amount"            numeric(18,2) NOT NULL,
    "GstAmount"         numeric(18,2) NOT NULL DEFAULT 0,
    "TotalAmount"       numeric(19,2) GENERATED ALWAYS AS ("Amount" + "GstAmount") STORED,
    "ReferenceNumber"   varchar(60),
    "BillNumber"        varchar(50),
    "AttachmentPath"    varchar(300),
    "Description"       varchar(500),
    "Status"            varchar(15)   NOT NULL DEFAULT 'Posted',
    "FinancialYearId"   int,
    "CreatedAt"         timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedBy"         int,
    "UpdatedAt"         timestamp(3),
    "UpdatedBy"         int,
    CONSTRAINT "PK_Expenses" PRIMARY KEY ("ExpenseId"),
    CONSTRAINT "UQ_Expenses_VoucherNumber" UNIQUE ("VoucherNumber"),
    CONSTRAINT "CK_Expenses_Amount" CHECK ("Amount" > 0 AND "GstAmount" >= 0),
    CONSTRAINT "CK_Expenses_Status" CHECK ("Status" IN ('Cancelled','Posted'))
);

CREATE INDEX "IX_Expenses_Category"
    ON "Expenses" ("ExpenseCategoryId", "ExpenseDate") INCLUDE ("TotalAmount", "Status");
CREATE INDEX "IX_Expenses_Date"
    ON "Expenses" ("ExpenseDate") INCLUDE ("ExpenseCategoryId", "Amount", "GstAmount", "TotalAmount", "Status");
