/*==============================================================================
  AgriERP  |  09_system.sql   (PostgreSQL)
  ------------------------------------------------------------------------------
  Singleton company profile, financial years, document number series, app
  settings, audit log and the navigation module master. PostgreSQL parallel of
  database/scripts/09_System.sql (+ 13_Modules). FKs in 80_foreign_keys.sql,
  ROWVERSION dropped.
==============================================================================*/

/* Singleton - a single row, id fixed at 1 by the CHECK. */
CREATE TABLE "CompanyProfile"
(
    "CompanyProfileId"    int          NOT NULL DEFAULT 1,
    "ShopName"            varchar(150) NOT NULL,
    "LegalName"           varchar(150),
    "GstNumber"           varchar(15),
    "PanNumber"           varchar(10),
    "PesticideLicenceNo"  varchar(50),
    "SeedLicenceNo"       varchar(50),
    "FertilizerLicenceNo" varchar(50),
    "AddressLine1"        varchar(200),
    "AddressLine2"        varchar(200),
    "City"                varchar(80),
    "StateId"             int,
    "Pincode"             varchar(6),
    "Phone"               varchar(15),
    "AlternatePhone"      varchar(15),
    "Email"               varchar(150),
    "Website"             varchar(200),
    "BankName"            varchar(120),
    "BankAccountNumber"   varchar(30),
    "BankIfsc"            varchar(11),
    "BankBranch"          varchar(120),
    "UpiId"               varchar(100),
    "LogoPath"            varchar(300),
    "InvoiceTerms"        varchar(1000),
    "InvoiceFooterNote"   varchar(500),
    "UpdatedAt"           timestamp(3),
    "UpdatedBy"           int,
    CONSTRAINT "PK_CompanyProfile" PRIMARY KEY ("CompanyProfileId"),
    CONSTRAINT "CK_CompanyProfile_Singleton" CHECK ("CompanyProfileId" = 1)
);

CREATE TABLE "FinancialYears"
(
    "FinancialYearId" int          GENERATED BY DEFAULT AS IDENTITY,
    "YearCode"        varchar(10)  NOT NULL,
    "StartDate"       date         NOT NULL,
    "EndDate"         date         NOT NULL,
    "IsActive"        boolean      NOT NULL DEFAULT false,
    "IsClosed"        boolean      NOT NULL DEFAULT false,
    "ClosedAt"        timestamp(3),
    "ClosedBy"        int,
    "CreatedAt"       timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_FinancialYears" PRIMARY KEY ("FinancialYearId"),
    CONSTRAINT "UQ_FinancialYears_YearCode" UNIQUE ("YearCode"),
    CONSTRAINT "CK_FinancialYears_Dates" CHECK ("EndDate" > "StartDate")
);

/* Only one active financial year at a time. */
CREATE UNIQUE INDEX "UQ_FinancialYears_Active"
    ON "FinancialYears" ("IsActive") WHERE "IsActive" = true;

CREATE TABLE "NumberSeries"
(
    "NumberSeriesId"  int          GENERATED BY DEFAULT AS IDENTITY,
    "DocumentType"    varchar(30)  NOT NULL,
    "FinancialYearId" int,
    "Prefix"          varchar(20)  NOT NULL DEFAULT '',
    "Suffix"          varchar(20)  NOT NULL DEFAULT '',
    "Separator"       varchar(3)   NOT NULL DEFAULT '/',
    "IncludeYearCode" boolean      NOT NULL DEFAULT true,
    "CurrentNumber"   int          NOT NULL DEFAULT 0,
    "PaddingLength"   smallint     NOT NULL DEFAULT 5,
    "IsActive"        boolean      NOT NULL DEFAULT true,
    "UpdatedAt"       timestamp(3),
    CONSTRAINT "PK_NumberSeries" PRIMARY KEY ("NumberSeriesId"),
    CONSTRAINT "CK_NumberSeries_CurrentNumber" CHECK ("CurrentNumber" >= 0),
    CONSTRAINT "CK_NumberSeries_PaddingLength" CHECK ("PaddingLength" >= 1 AND "PaddingLength" <= 12)
);

-- NULLS NOT DISTINCT so a null FinancialYearId is unique per DocumentType,
-- matching SQL Server's single-NULL unique-index semantics.
CREATE UNIQUE INDEX "UQ_NumberSeries_Type_Year"
    ON "NumberSeries" ("DocumentType", "FinancialYearId") NULLS NOT DISTINCT;

CREATE TABLE "AppSettings"
(
    "SettingId"    int          GENERATED BY DEFAULT AS IDENTITY,
    "SettingKey"   varchar(80)  NOT NULL,
    "SettingValue" varchar(500),
    "DataType"     varchar(20)  NOT NULL DEFAULT 'string',
    "Category"     varchar(40),
    "Description"  varchar(300),
    "IsSystem"     boolean      NOT NULL DEFAULT false,
    "UpdatedAt"    timestamp(3),
    "UpdatedBy"    int,
    CONSTRAINT "PK_AppSettings" PRIMARY KEY ("SettingId"),
    CONSTRAINT "UQ_AppSettings_SettingKey" UNIQUE ("SettingKey"),
    CONSTRAINT "CK_AppSettings_DataType" CHECK ("DataType" IN ('json','date','bool','decimal','int','string'))
);

CREATE TABLE "AuditLogs"
(
    "AuditLogId"      bigint        GENERATED BY DEFAULT AS IDENTITY,
    "TableName"       varchar(120)  NOT NULL,
    "PrimaryKeyValue" varchar(60),
    "Action"          varchar(10)   NOT NULL,
    "OldValues"       text,
    "NewValues"       text,
    "ChangedColumns"  varchar(1000),
    "UserId"          int,
    "UserName"        varchar(60),
    "IpAddress"       varchar(45),
    "RequestId"       varchar(50),
    "LoggedAt"        timestamp(3)  NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("AuditLogId"),
    CONSTRAINT "CK_AuditLogs_Action" CHECK ("Action" IN ('Delete','Update','Insert'))
);

CREATE INDEX "IX_AuditLogs_LoggedAt"  ON "AuditLogs" ("LoggedAt");
CREATE INDEX "IX_AuditLogs_Table_Key" ON "AuditLogs" ("TableName", "PrimaryKeyValue", "LoggedAt");
CREATE INDEX "IX_AuditLogs_User_Date" ON "AuditLogs" ("UserId", "LoggedAt") INCLUDE ("TableName", "Action");

CREATE TABLE "ModuleMaster"
(
    "ModuleID"               int          GENERATED BY DEFAULT AS IDENTITY,
    "ModuleName"             varchar(200) NOT NULL,
    "ModuleDisplayName"      varchar(200) NOT NULL,
    "ModuleHeadName"         varchar(100) NOT NULL,
    "ModuleHeadDisplayName"  varchar(100) NOT NULL,
    "ModuleHeadDisplayOrder" int          NOT NULL,
    "ModuleDisplayOrder"     int          NOT NULL,
    "SetGroupIndex"          int          NOT NULL,
    "IconName"               varchar(100),
    "IsDeletedTransaction"   boolean      NOT NULL DEFAULT false,
    "CreatedDate"            timestamp(3) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_ModuleMaster" PRIMARY KEY ("ModuleID")
);

CREATE INDEX "IX_ModuleMaster_Display"
    ON "ModuleMaster" ("IsDeletedTransaction", "ModuleHeadDisplayOrder", "ModuleDisplayOrder")
    INCLUDE ("ModuleName", "ModuleDisplayName", "ModuleHeadName", "ModuleHeadDisplayName", "SetGroupIndex", "IconName");
CREATE UNIQUE INDEX "UQ_ModuleMaster_ModuleName"
    ON "ModuleMaster" ("ModuleName") WHERE "IsDeletedTransaction" = false;
